name: 'node composite'
runs: 
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3
    -name: using node 16
      uses: actions/setup-node@v3
      with:
        node-version: "16.X"
        cache: "npm"
    - run: npm ci 
      shell: bash

